version: '3.9'
networks:
  nest:
    driver: bridge
volumes:
  starterkit-mysql:
    driver: local
services:
  starterkit:
    container_name: '${APP_NAME}_api'
    environment:
      NODE_ENV: 'development'
    restart: always
    command: npm run start:dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    image: starterkit/latest
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - .:/src/app
    networks:
      - nest
    depends_on:
      - mysql

  mysql:
    container_name: '${APP_NAME}_db'
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DATABASE_NAME}'
      MYSQL_USER: '${DATABASE_USERNAME}'
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - nest
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DATABASE_PASSWORD}"]
      retries: 3
      timeout: 5s
  phpmyadmin:
    container_name: '${APP_NAME}_phpmyadmin'
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    ports:
      - '8080:80'
    environment:
      MYSQL_USERNAME: "${DATABASE_USERNAME}"
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
      PMA_HOST: mysql
    networks:
      - nest
    depends_on:
      - mysql